### PR TITLE
Parsed through the JSON

### PR DESCRIPTION
**Pull request by RookTKO**
I got it working for Time Series Daily. It consoles all the objects key pair values into the console. Haven't gotten around to checking the other ones. I recommend you merge this with the original copy and also download the json file so there is a static file for all of the options because I'm pretty sure I exhausted all the API calls for the day working on it.

### CODE REVIEW

**Comment by DaSunnySide** [comment]
Olaf, just now realizing I don't know how to merge changes lol. Not quite as intuitive as I was expecting. How do I approve them?

**Comment by DaSunnySide** [comment]
I already approved the changes but I dont' know how to resolve the conflicts I guess

**Comment by RookTKO** [comment]
Give me write access and I can go through it and resolve the conflicts.

**Comment by RookTKO** [comment]
Done. Combined merged files.

**Pull request merged**
